### PR TITLE
Updated color palette color, added Table for contacts number

### PR DESCRIPTION
**Pull request by worldwidey**
- For the color palette, I deleted soft[5] and change the order to make primary[1] show up in our piechart.
- For the weekly_report, I added table1 which is summary statistics of an average number of contacts per case by person_type. Since Kelly asked four groups, I made a table based on her draft order. (Students, Employee, Both, and Others). 
- The line 296 and 299 were modified as the value showed up as a table rather than the number in our report. This change may occur since we now have a table in R markdown? (unsure, but it works fine with current code.)

### CODE REVIEW

**Comment by pbchase** [comment]
Your use of `huxtable` injected complexity into the package I could not address on my own. It has more tex package requirements I do not meet locally. Do you need it? Have you tried kable?

Also, we are merging person_type == JAX into person_type == EMPLOYEE.  See https://github.com/ctsit/tt_reporting/pull/42 that PR is not yet merged, but you might want to merge it into your own so as to simplify your code additions.

**Comment by worldwidey** [comment]
> Your use of `huxtable` injected complexity into the package I could not address on my own. It has more tex package requirements I do not meet locally. Do you need it? Have you tried kable?
> 
> Also, we are merging person_type == JAX into person_type == EMPLOYEE. See #42 that PR is not yet merged, but you might want to merge it into your own so as to simplify your code additions.

Sure, I can use kable. I will start from the latest file and will update the table code with kable. Thank you for reminding JAX change!

**Comment by pbchase** [comment]
@worldwidey, the develop branch now has the code to merge person_type == JAX into person_type == EMPLOYEE.

**Comment by worldwidey** [comment]
> @worldwidey, the develop branch now has the code to merge person_type == JAX into person_type == EMPLOYEE.

Thanks for the update! I will start updating the latest version of the code.

**Comment by ljwoodley** [comment]
This PR was replaced with PR #45

**Pull request closed without merging**
